name: gdpr-evenness
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pandas
      - polars
      - pyarrow
      - statsmodels
      - linearmodels
      - scikit-learn
      - seaborn
      - matplotlib
      - shap
      - scipy
      - tqdm
      - gower
