
# GDPR DPA Decisions Dataset Loading Script
# Generated automatically from Python export

library(dplyr)
library(readr)
library(forcats)

# Load the data
gdpr_data <- read_csv("gdpr_decisions.csv")

# Convert categorical variables to factors with proper levels
gdpr_data$country_group <- factor(gdpr_data$country_group, levels = c("EU", "EEA", "NON_EEA"), ordered = FALSE)
gdpr_data$decision_quarter <- factor(gdpr_data$decision_quarter, levels = c("Q1", "Q2", "Q3", "Q4"), ordered = TRUE)

# Convert date variables
gdpr_data$decision_date <- as.Date(gdpr_data$decision_date)

# Add variable labels (requires Hmisc package)
if (require(Hmisc)) {
  label(gdpr_data$decision_id) <- "Unique decision identifier"
  label(gdpr_data$ingest_parser_version) <- "Ingest Parser Version"
  label(gdpr_data$ingest_line_count) <- "Ingest Line Count"
  label(gdpr_data$ingest_question_count) <- "Ingest Question Count"
  label(gdpr_data$ingest_missing_questions) <- "Ingest Missing Questions"
  label(gdpr_data$ingest_warning_count) <- "Ingest Warning Count"
  label(gdpr_data$ingest_warnings) <- "Ingest Warnings"
  label(gdpr_data$country_code) <- "ISO country code of deciding authority"
  label(gdpr_data$country_status) <- "Status of country information"
  label(gdpr_data$country_group) <- "Geographic grouping (EU/EEA/NON_EEA)"
  label(gdpr_data$country_mapped_from_uk) <- "Country Mapped From Uk"
  label(gdpr_data$country_whitelist_ok) <- "Country Whitelist Ok"
  label(gdpr_data$dpa_name_raw) <- "Dpa Name Raw"
  label(gdpr_data$dpa_name_canonical) <- "Standardized DPA name"
  label(gdpr_data$decision_date_raw) <- "Decision Date Raw"
  label(gdpr_data$decision_date) <- "Date of decision issuance"
  label(gdpr_data$decision_date_status) <- "Status of decision_date information"
  label(gdpr_data$decision_date_error) <- "Decision Date Error"
  label(gdpr_data$decision_year) <- "Year of decision"
  label(gdpr_data$decision_quarter) <- "Quarter of decision year"
  label(gdpr_data$fine_eur) <- "Administrative fine amount (EUR)"
  label(gdpr_data$fine_numeric_valid) <- "Fine Numeric Valid"
  label(gdpr_data$fine_positive) <- "Whether fine > 0 was imposed"
  label(gdpr_data$fine_log1p) <- "Fine Log1P"
  label(gdpr_data$fine_outlier_flag) <- "Fine Outlier Flag"
  label(gdpr_data$fine_raw) <- "Fine Raw"
  label(gdpr_data$fine_status) <- "Status of fine information"
  label(gdpr_data$fine_error) <- "Fine Error"
  label(gdpr_data$turnover_eur) <- "Annual turnover mentioned (EUR)"
  label(gdpr_data$turnover_numeric_valid) <- "Turnover Numeric Valid"
  label(gdpr_data$turnover_positive) <- "Turnover Positive"
  label(gdpr_data$turnover_log1p) <- "Turnover Log1P"
  label(gdpr_data$turnover_outlier_flag) <- "Turnover Outlier Flag"
  label(gdpr_data$turnover_raw) <- "Turnover Raw"
  label(gdpr_data$turnover_status) <- "Status of turnover information"
  label(gdpr_data$turnover_error) <- "Turnover Error"
  label(gdpr_data$fine_to_turnover_ratio) <- "Fine To Turnover Ratio"
  label(gdpr_data$isic_code) <- "Isic Code"
  label(gdpr_data$isic_desc) <- "Isic Desc"
  label(gdpr_data$isic_section) <- "Isic Section"
  label(gdpr_data$n_principles_discussed) <- "Number of Article 5 principles discussed"
  label(gdpr_data$n_principles_violated) <- "Number of Article 5 principles violated"
  label(gdpr_data$n_corrective_measures) <- "Number of corrective measures imposed"
  label(gdpr_data$severity_measures_present) <- "Whether severe measures imposed"
  label(gdpr_data$remedy_only_case) <- "Remedy Only Case"
  label(gdpr_data$breach_case) <- "Whether data breach was discussed"
  label(gdpr_data$q36_text) <- "Q36 Text"
  label(gdpr_data$q36_lang) <- "Q36 Lang"
  label(gdpr_data$q36_tokens) <- "Q36 Tokens"
  label(gdpr_data$q52_text) <- "Q52 Text"
  label(gdpr_data$q52_lang) <- "Q52 Lang"
  label(gdpr_data$q52_tokens) <- "Q52 Tokens"
  label(gdpr_data$q67_text) <- "Q67 Text"
  label(gdpr_data$q67_lang) <- "Q67 Lang"
  label(gdpr_data$q67_tokens) <- "Q67 Tokens"
  label(gdpr_data$q68_text) <- "Q68 Text"
  label(gdpr_data$q68_lang) <- "Q68 Lang"
  label(gdpr_data$q68_tokens) <- "Q68 Tokens"
  label(gdpr_data$schema_echo_flag) <- "Schema Echo Flag"
  label(gdpr_data$schema_echo_fields) <- "Schema Echo Fields"
  label(gdpr_data$raw_q1) <- "Raw Q1"
  label(gdpr_data$raw_q2) <- "Raw Q2"
  label(gdpr_data$raw_q3) <- "Raw Q3"
  label(gdpr_data$raw_q4) <- "Raw Q4"
  label(gdpr_data$raw_q5) <- "Raw Q5"
  label(gdpr_data$raw_q6) <- "Raw Q6"
  label(gdpr_data$raw_q7) <- "Raw Q7"
  label(gdpr_data$raw_q8) <- "Raw Q8"
  label(gdpr_data$raw_q9) <- "Raw Q9"
  label(gdpr_data$raw_q10) <- "Raw Q10"
  label(gdpr_data$raw_q11) <- "Raw Q11"
  label(gdpr_data$raw_q12) <- "Raw Q12"
  label(gdpr_data$raw_q13) <- "Raw Q13"
  label(gdpr_data$raw_q14) <- "Raw Q14"
  label(gdpr_data$raw_q15) <- "Raw Q15"
  label(gdpr_data$raw_q16) <- "Raw Q16"
  label(gdpr_data$raw_q17) <- "Raw Q17"
  label(gdpr_data$raw_q18) <- "Raw Q18"
  label(gdpr_data$raw_q19) <- "Raw Q19"
  label(gdpr_data$raw_q20) <- "Raw Q20"
  label(gdpr_data$raw_q21) <- "Raw Q21"
  label(gdpr_data$raw_q22) <- "Raw Q22"
  label(gdpr_data$raw_q23) <- "Raw Q23"
  label(gdpr_data$raw_q24) <- "Raw Q24"
  label(gdpr_data$raw_q25) <- "Raw Q25"
  label(gdpr_data$raw_q26) <- "Raw Q26"
  label(gdpr_data$raw_q27) <- "Raw Q27"
  label(gdpr_data$raw_q28) <- "Raw Q28"
  label(gdpr_data$raw_q29) <- "Raw Q29"
  label(gdpr_data$raw_q30) <- "Raw Q30"
  label(gdpr_data$raw_q31) <- "Raw Q31"
  label(gdpr_data$raw_q32) <- "Raw Q32"
  label(gdpr_data$raw_q33) <- "Raw Q33"
  label(gdpr_data$raw_q34) <- "Raw Q34"
  label(gdpr_data$raw_q35) <- "Raw Q35"
  label(gdpr_data$raw_q36) <- "Raw Q36"
  label(gdpr_data$raw_q37) <- "Raw Q37"
  label(gdpr_data$raw_q38) <- "Raw Q38"
  label(gdpr_data$raw_q39) <- "Raw Q39"
  label(gdpr_data$raw_q40) <- "Raw Q40"
  label(gdpr_data$raw_q41) <- "Raw Q41"
  label(gdpr_data$raw_q42) <- "Raw Q42"
  label(gdpr_data$raw_q43) <- "Raw Q43"
  label(gdpr_data$raw_q44) <- "Raw Q44"
  label(gdpr_data$raw_q45) <- "Raw Q45"
  label(gdpr_data$raw_q46) <- "Raw Q46"
  label(gdpr_data$raw_q47) <- "Raw Q47"
  label(gdpr_data$raw_q48) <- "Raw Q48"
  label(gdpr_data$raw_q49) <- "Raw Q49"
  label(gdpr_data$raw_q50) <- "Raw Q50"
  label(gdpr_data$raw_q51) <- "Raw Q51"
  label(gdpr_data$raw_q52) <- "Raw Q52"
  label(gdpr_data$raw_q53) <- "Raw Q53"
  label(gdpr_data$raw_q54) <- "Raw Q54"
  label(gdpr_data$raw_q55) <- "Raw Q55"
  label(gdpr_data$raw_q56) <- "Raw Q56"
  label(gdpr_data$raw_q57) <- "Raw Q57"
  label(gdpr_data$raw_q58) <- "Raw Q58"
  label(gdpr_data$raw_q59) <- "Raw Q59"
  label(gdpr_data$raw_q60) <- "Raw Q60"
  label(gdpr_data$raw_q61) <- "Raw Q61"
  label(gdpr_data$raw_q62) <- "Raw Q62"
  label(gdpr_data$raw_q63) <- "Raw Q63"
  label(gdpr_data$raw_q64) <- "Raw Q64"
  label(gdpr_data$raw_q65) <- "Raw Q65"
  label(gdpr_data$raw_q66) <- "Raw Q66"
  label(gdpr_data$raw_q67) <- "Raw Q67"
  label(gdpr_data$raw_q68) <- "Raw Q68"
  label(gdpr_data$q30_discussed_coverage_status) <- "Article 5 principle discussed: coverage_status"
  label(gdpr_data$q30_discussed_known) <- "Article 5 principle discussed: known"
  label(gdpr_data$q30_discussed_unknown) <- "Article 5 principle discussed: unknown"
  label(gdpr_data$q30_discussed_status) <- "Article 5 principle discussed: status"
  label(gdpr_data$q30_discussed_exclusivity_conflict) <- "Article 5 principle discussed: exclusivity_conflict"
  label(gdpr_data$q30_discussed_LAWFULNESS_FAIRNESS_TRANSPARENCY) <- "Article 5 principle discussed: LAWFULNESS_FAIRNESS_TRANSPARENCY"
  label(gdpr_data$q30_discussed_PURPOSE_LIMITATION) <- "Article 5 principle discussed: PURPOSE_LIMITATION"
  label(gdpr_data$q30_discussed_DATA_MINIMISATION) <- "Article 5 principle discussed: DATA_MINIMISATION"
  label(gdpr_data$q30_discussed_ACCURACY) <- "Article 5 principle discussed: ACCURACY"
  label(gdpr_data$q30_discussed_STORAGE_LIMITATION) <- "Article 5 principle discussed: STORAGE_LIMITATION"
  label(gdpr_data$q30_discussed_SECURITY) <- "Article 5 principle discussed: SECURITY"
  label(gdpr_data$q30_discussed_ACCOUNTABILITY) <- "Article 5 principle discussed: ACCOUNTABILITY"
  label(gdpr_data$q30_discussed_NONE_DISCUSSED) <- "Article 5 principle discussed: NONE_DISCUSSED"
  label(gdpr_data$q31_violated_coverage_status) <- "Article 5 principle violated: coverage_status"
  label(gdpr_data$q31_violated_known) <- "Article 5 principle violated: known"
  label(gdpr_data$q31_violated_unknown) <- "Article 5 principle violated: unknown"
  label(gdpr_data$q31_violated_status) <- "Article 5 principle violated: status"
  label(gdpr_data$q31_violated_exclusivity_conflict) <- "Article 5 principle violated: exclusivity_conflict"
  label(gdpr_data$q31_violated_LAWFULNESS_FAIRNESS_TRANSPARENCY) <- "Article 5 principle violated: LAWFULNESS_FAIRNESS_TRANSPARENCY"
  label(gdpr_data$q31_violated_PURPOSE_LIMITATION) <- "Article 5 principle violated: PURPOSE_LIMITATION"
  label(gdpr_data$q31_violated_DATA_MINIMISATION) <- "Article 5 principle violated: DATA_MINIMISATION"
  label(gdpr_data$q31_violated_ACCURACY) <- "Article 5 principle violated: ACCURACY"
  label(gdpr_data$q31_violated_STORAGE_LIMITATION) <- "Article 5 principle violated: STORAGE_LIMITATION"
  label(gdpr_data$q31_violated_SECURITY) <- "Article 5 principle violated: SECURITY"
  label(gdpr_data$q31_violated_ACCOUNTABILITY) <- "Article 5 principle violated: ACCOUNTABILITY"
  label(gdpr_data$q31_violated_NONE_VIOLATED) <- "Article 5 principle violated: NONE_VIOLATED"
  label(gdpr_data$q31_violated_NOT_DETERMINED) <- "Article 5 principle violated: NOT_DETERMINED"
  label(gdpr_data$q32_bases_coverage_status) <- "Status of q32_bases_coverage information"
  label(gdpr_data$q32_bases_known) <- "Q32 Bases Known"
  label(gdpr_data$q32_bases_unknown) <- "Q32 Bases Unknown"
  label(gdpr_data$q32_bases_status) <- "Status of q32_bases information"
  label(gdpr_data$q32_bases_exclusivity_conflict) <- "Q32 Bases Exclusivity Conflict"
  label(gdpr_data$q32_bases_CONSENT) <- "Q32 Bases Consent"
  label(gdpr_data$q32_bases_CONTRACT) <- "Q32 Bases Contract"
  label(gdpr_data$q32_bases_LEGAL_OBLIGATION) <- "Q32 Bases Legal Obligation"
  label(gdpr_data$q32_bases_VITAL_INTERESTS) <- "Q32 Bases Vital Interests"
  label(gdpr_data$q32_bases_PUBLIC_TASK) <- "Q32 Bases Public Task"
  label(gdpr_data$q32_bases_LEGITIMATE_INTERESTS) <- "Q32 Bases Legitimate Interests"
  label(gdpr_data$q32_bases_NONE_DISCUSSED) <- "Q32 Bases None Discussed"
  label(gdpr_data$q41_aggrav_coverage_status) <- "Status of q41_aggrav_coverage information"
  label(gdpr_data$q41_aggrav_known) <- "Q41 Aggrav Known"
  label(gdpr_data$q41_aggrav_unknown) <- "Q41 Aggrav Unknown"
  label(gdpr_data$q41_aggrav_status) <- "Status of q41_aggrav information"
  label(gdpr_data$q41_aggrav_exclusivity_conflict) <- "Q41 Aggrav Exclusivity Conflict"
  label(gdpr_data$q41_aggrav_NATURE_GRAVITY_DURATION) <- "Q41 Aggrav Nature Gravity Duration"
  label(gdpr_data$q41_aggrav_INTENT_NEGLIGENCE) <- "Q41 Aggrav Intent Negligence"
  label(gdpr_data$q41_aggrav_MITIGATION_ACTIONS) <- "Q41 Aggrav Mitigation Actions"
  label(gdpr_data$q41_aggrav_TECHNICAL_ORGANIZATIONAL_MEASURES) <- "Q41 Aggrav Technical Organizational Measures"
  label(gdpr_data$q41_aggrav_PREVIOUS_INFRINGEMENTS) <- "Q41 Aggrav Previous Infringements"
  label(gdpr_data$q41_aggrav_COOPERATION_WITH_AUTHORITY) <- "Q41 Aggrav Cooperation With Authority"
  label(gdpr_data$q41_aggrav_DATA_CATEGORIES_AFFECTED) <- "Q41 Aggrav Data Categories Affected"
  label(gdpr_data$q41_aggrav_MANNER_BECAME_KNOWN) <- "Q41 Aggrav Manner Became Known"
  label(gdpr_data$q41_aggrav_COMPLIANCE_PRIOR_ORDERS) <- "Q41 Aggrav Compliance Prior Orders"
  label(gdpr_data$q41_aggrav_CODES_CERTIFICATION) <- "Q41 Aggrav Codes Certification"
  label(gdpr_data$q41_aggrav_OTHER_CIRCUMSTANCES) <- "Q41 Aggrav Other Circumstances"
  label(gdpr_data$q41_aggrav_NONE) <- "Q41 Aggrav None"
  label(gdpr_data$q42_mitig_coverage_status) <- "Status of q42_mitig_coverage information"
  label(gdpr_data$q42_mitig_known) <- "Q42 Mitig Known"
  label(gdpr_data$q42_mitig_unknown) <- "Q42 Mitig Unknown"
  label(gdpr_data$q42_mitig_status) <- "Status of q42_mitig information"
  label(gdpr_data$q42_mitig_exclusivity_conflict) <- "Q42 Mitig Exclusivity Conflict"
  label(gdpr_data$q42_mitig_NATURE_GRAVITY_DURATION) <- "Q42 Mitig Nature Gravity Duration"
  label(gdpr_data$q42_mitig_INTENT_NEGLIGENCE) <- "Q42 Mitig Intent Negligence"
  label(gdpr_data$q42_mitig_MITIGATION_ACTIONS) <- "Q42 Mitig Mitigation Actions"
  label(gdpr_data$q42_mitig_TECHNICAL_ORGANIZATIONAL_MEASURES) <- "Q42 Mitig Technical Organizational Measures"
  label(gdpr_data$q42_mitig_PREVIOUS_INFRINGEMENTS) <- "Q42 Mitig Previous Infringements"
  label(gdpr_data$q42_mitig_COOPERATION_WITH_AUTHORITY) <- "Q42 Mitig Cooperation With Authority"
  label(gdpr_data$q42_mitig_DATA_CATEGORIES_AFFECTED) <- "Q42 Mitig Data Categories Affected"
  label(gdpr_data$q42_mitig_MANNER_BECAME_KNOWN) <- "Q42 Mitig Manner Became Known"
  label(gdpr_data$q42_mitig_COMPLIANCE_PRIOR_ORDERS) <- "Q42 Mitig Compliance Prior Orders"
  label(gdpr_data$q42_mitig_CODES_CERTIFICATION) <- "Q42 Mitig Codes Certification"
  label(gdpr_data$q42_mitig_OTHER_CIRCUMSTANCES) <- "Q42 Mitig Other Circumstances"
  label(gdpr_data$q42_mitig_NONE) <- "Q42 Mitig None"
  label(gdpr_data$q43_harm_coverage_status) <- "Q43 Harm Coverage Status"
  label(gdpr_data$q43_harm_known) <- "Q43 Harm Known"
  label(gdpr_data$q43_harm_unknown) <- "Q43 Harm Unknown"
  label(gdpr_data$q43_harm_status) <- "Q43 Harm Status"
  label(gdpr_data$q43_harm_exclusivity_conflict) <- "Q43 Harm Exclusivity Conflict"
  label(gdpr_data$q43_harm_YES_MATERIAL_HARM) <- "Q43 Harm Yes Material Harm"
  label(gdpr_data$q43_harm_YES_NON_MATERIAL_HARM) <- "Q43 Harm Yes Non Material Harm"
  label(gdpr_data$q43_harm_YES_BOTH_TYPES) <- "Q43 Harm Yes Both Types"
  label(gdpr_data$q43_harm_NO_HARM_DOCUMENTED) <- "Q43 Harm No Harm Documented"
  label(gdpr_data$q43_harm_NO) <- "Q43 Harm No"
  label(gdpr_data$q43_harm_NOT_DISCUSSED) <- "Q43 Harm Not Discussed"
  label(gdpr_data$q43_harm_UNCLEAR) <- "Q43 Harm Unclear"
  label(gdpr_data$q44_benefit_coverage_status) <- "Q44 Benefit Coverage Status"
  label(gdpr_data$q44_benefit_known) <- "Q44 Benefit Known"
  label(gdpr_data$q44_benefit_unknown) <- "Q44 Benefit Unknown"
  label(gdpr_data$q44_benefit_status) <- "Q44 Benefit Status"
  label(gdpr_data$q44_benefit_exclusivity_conflict) <- "Q44 Benefit Exclusivity Conflict"
  label(gdpr_data$q44_benefit_YES_QUANTIFIED) <- "Q44 Benefit Yes Quantified"
  label(gdpr_data$q44_benefit_YES_MENTIONED_UNQUANTIFIED) <- "Q44 Benefit Yes Mentioned Unquantified"
  label(gdpr_data$q44_benefit_NO_BENEFIT) <- "Q44 Benefit No Benefit"
  label(gdpr_data$q44_benefit_NO) <- "Q44 Benefit No"
  label(gdpr_data$q44_benefit_NOT_DISCUSSED) <- "Q44 Benefit Not Discussed"
  label(gdpr_data$q44_benefit_UNCLEAR) <- "Q44 Benefit Unclear"
  label(gdpr_data$q45_coop_coverage_status) <- "Q45 Cooperation Coverage Status"
  label(gdpr_data$q45_coop_known) <- "Q45 Cooperation Known"
  label(gdpr_data$q45_coop_unknown) <- "Q45 Cooperation Unknown"
  label(gdpr_data$q45_coop_status) <- "Q45 Cooperation Status"
  label(gdpr_data$q45_coop_exclusivity_conflict) <- "Q45 Cooperation Exclusivity Conflict"
  label(gdpr_data$q45_coop_FULL_COOPERATION) <- "Q45 Cooperation Full Cooperation"
  label(gdpr_data$q45_coop_PARTIAL_COOPERATION) <- "Q45 Cooperation Partial Cooperation"
  label(gdpr_data$q45_coop_NON_COOPERATIVE) <- "Q45 Cooperation Non Cooperative"
  label(gdpr_data$q45_coop_OBSTRUCTIVE) <- "Q45 Cooperation Obstructive"
  label(gdpr_data$q45_coop_NO) <- "Q45 Cooperation No"
  label(gdpr_data$q45_coop_NOT_DISCUSSED) <- "Q45 Cooperation Not Discussed"
  label(gdpr_data$q45_coop_UNCLEAR) <- "Q45 Cooperation Unclear"
  label(gdpr_data$q46_vuln_coverage_status) <- "Status of q46_vuln_coverage information"
  label(gdpr_data$q46_vuln_known) <- "Q46 Vuln Known"
  label(gdpr_data$q46_vuln_unknown) <- "Q46 Vuln Unknown"
  label(gdpr_data$q46_vuln_status) <- "Status of q46_vuln information"
  label(gdpr_data$q46_vuln_exclusivity_conflict) <- "Q46 Vuln Exclusivity Conflict"
  label(gdpr_data$q46_vuln_CHILDREN) <- "Q46 Vuln Children"
  label(gdpr_data$q46_vuln_ELDERLY) <- "Q46 Vuln Elderly"
  label(gdpr_data$q46_vuln_PATIENTS) <- "Q46 Vuln Patients"
  label(gdpr_data$q46_vuln_EMPLOYEES) <- "Q46 Vuln Employees"
  label(gdpr_data$q46_vuln_FINANCIALLY_VULNERABLE) <- "Q46 Vuln Financially Vulnerable"
  label(gdpr_data$q46_vuln_NONE_MENTIONED) <- "Q46 Vuln None Mentioned"
  label(gdpr_data$q46_vuln_NOT_DISCUSSED) <- "Q46 Vuln Not Discussed"
  label(gdpr_data$q47_remedial_coverage_status) <- "Status of q47_remedial_coverage information"
  label(gdpr_data$q47_remedial_known) <- "Q47 Remedial Known"
  label(gdpr_data$q47_remedial_unknown) <- "Q47 Remedial Unknown"
  label(gdpr_data$q47_remedial_status) <- "Status of q47_remedial information"
  label(gdpr_data$q47_remedial_exclusivity_conflict) <- "Q47 Remedial Exclusivity Conflict"
  label(gdpr_data$q47_remedial_IMMEDIATE_CESSATION) <- "Q47 Remedial Immediate Cessation"
  label(gdpr_data$q47_remedial_SYSTEM_UPGRADES) <- "Q47 Remedial System Upgrades"
  label(gdpr_data$q47_remedial_POLICY_CHANGES) <- "Q47 Remedial Policy Changes"
  label(gdpr_data$q47_remedial_STAFF_TRAINING) <- "Q47 Remedial Staff Training"
  label(gdpr_data$q47_remedial_EXTERNAL_AUDIT) <- "Q47 Remedial External Audit"
  label(gdpr_data$q47_remedial_DPO_APPOINTMENT) <- "Q47 Remedial Dpo Appointment"
  label(gdpr_data$q47_remedial_COMPENSATION_TO_SUBJECTS) <- "Q47 Remedial Compensation To Subjects"
  label(gdpr_data$q47_remedial_NONE_MENTIONED) <- "Q47 Remedial None Mentioned"
  label(gdpr_data$q50_other_measures_coverage_status) <- "Status of q50_other_measures_coverage information"
  label(gdpr_data$q50_other_measures_known) <- "Q50 Other Measures Known"
  label(gdpr_data$q50_other_measures_unknown) <- "Q50 Other Measures Unknown"
  label(gdpr_data$q50_other_measures_status) <- "Status of q50_other_measures information"
  label(gdpr_data$q50_other_measures_exclusivity_conflict) <- "Q50 Other Measures Exclusivity Conflict"
  label(gdpr_data$q50_other_measures_PROCESSING_BAN) <- "Q50 Other Measures Processing Ban"
  label(gdpr_data$q50_other_measures_DATA_DELETION_ORDER) <- "Q50 Other Measures Data Deletion Order"
  label(gdpr_data$q50_other_measures_COMPLIANCE_ORDER) <- "Q50 Other Measures Compliance Order"
  label(gdpr_data$q50_other_measures_CERTIFICATION_WITHDRAWAL) <- "Q50 Other Measures Certification Withdrawal"
  label(gdpr_data$q50_other_measures_PERIODIC_REPORTING) <- "Q50 Other Measures Periodic Reporting"
  label(gdpr_data$q50_other_measures_AUDIT_REQUIREMENT) <- "Q50 Other Measures Audit Requirement"
  label(gdpr_data$q50_other_measures_NONE) <- "Q50 Other Measures None"
  label(gdpr_data$q53_powers_coverage_status) <- "Corrective power exercised: coverage_status"
  label(gdpr_data$q53_powers_known) <- "Corrective power exercised: known"
  label(gdpr_data$q53_powers_unknown) <- "Corrective power exercised: unknown"
  label(gdpr_data$q53_powers_status) <- "Corrective power exercised: status"
  label(gdpr_data$q53_powers_exclusivity_conflict) <- "Corrective power exercised: exclusivity_conflict"
  label(gdpr_data$q53_powers_WARNING) <- "Corrective power exercised: WARNING"
  label(gdpr_data$q53_powers_REPRIMAND) <- "Corrective power exercised: REPRIMAND"
  label(gdpr_data$q53_powers_COMPLY_WITH_DATA_SUBJECT_REQUESTS) <- "Corrective power exercised: COMPLY_WITH_DATA_SUBJECT_REQUESTS"
  label(gdpr_data$q53_powers_BRING_PROCESSING_INTO_COMPLIANCE) <- "Corrective power exercised: BRING_PROCESSING_INTO_COMPLIANCE"
  label(gdpr_data$q53_powers_COMMUNICATE_BREACH_TO_SUBJECTS) <- "Corrective power exercised: COMMUNICATE_BREACH_TO_SUBJECTS"
  label(gdpr_data$q53_powers_LIMITATION_PROHIBITION_OF_PROCESSING) <- "Corrective power exercised: LIMITATION_PROHIBITION_OF_PROCESSING"
  label(gdpr_data$q53_powers_RECTIFICATION_ERASURE_RESTRICTION) <- "Corrective power exercised: RECTIFICATION_ERASURE_RESTRICTION"
  label(gdpr_data$q53_powers_CERTIFICATION_WITHDRAWAL) <- "Corrective power exercised: CERTIFICATION_WITHDRAWAL"
  label(gdpr_data$q53_powers_ADMINISTRATIVE_FINE) <- "Corrective power exercised: ADMINISTRATIVE_FINE"
  label(gdpr_data$q53_powers_SUSPENSION_DATA_FLOWS) <- "Corrective power exercised: SUSPENSION_DATA_FLOWS"
  label(gdpr_data$q53_powers_NONE) <- "Corrective power exercised: NONE"
  label(gdpr_data$q54_scopes_coverage_status) <- "Status of q54_scopes_coverage information"
  label(gdpr_data$q54_scopes_known) <- "Q54 Scopes Known"
  label(gdpr_data$q54_scopes_unknown) <- "Q54 Scopes Unknown"
  label(gdpr_data$q54_scopes_status) <- "Status of q54_scopes information"
  label(gdpr_data$q54_scopes_exclusivity_conflict) <- "Q54 Scopes Exclusivity Conflict"
  label(gdpr_data$q54_scopes_COMPLETE_PROCESSING_BAN) <- "Q54 Scopes Complete Processing Ban"
  label(gdpr_data$q54_scopes_SPECIFIC_PURPOSE_LIMITATION) <- "Q54 Scopes Specific Purpose Limitation"
  label(gdpr_data$q54_scopes_DATA_CATEGORY_LIMITATION) <- "Q54 Scopes Data Category Limitation"
  label(gdpr_data$q54_scopes_GEOGRAPHICAL_LIMITATION) <- "Q54 Scopes Geographical Limitation"
  label(gdpr_data$q54_scopes_TEMPORAL_LIMITATION) <- "Q54 Scopes Temporal Limitation"
  label(gdpr_data$q54_scopes_NOT_APPLICABLE) <- "Q54 Scopes Not Applicable"
  label(gdpr_data$q56_rights_discussed_coverage_status) <- "Status of q56_rights_discussed_coverage information"
  label(gdpr_data$q56_rights_discussed_known) <- "Q56 Rights Discussed Known"
  label(gdpr_data$q56_rights_discussed_unknown) <- "Q56 Rights Discussed Unknown"
  label(gdpr_data$q56_rights_discussed_status) <- "Status of q56_rights_discussed information"
  label(gdpr_data$q56_rights_discussed_exclusivity_conflict) <- "Q56 Rights Discussed Exclusivity Conflict"
  label(gdpr_data$q56_rights_discussed_ACCESS) <- "Q56 Rights Discussed Access"
  label(gdpr_data$q56_rights_discussed_RECTIFICATION) <- "Q56 Rights Discussed Rectification"
  label(gdpr_data$q56_rights_discussed_ERASURE) <- "Q56 Rights Discussed Erasure"
  label(gdpr_data$q56_rights_discussed_RESTRICTION_OF_PROCESSING) <- "Q56 Rights Discussed Restriction Of Processing"
  label(gdpr_data$q56_rights_discussed_DATA_PORTABILITY) <- "Q56 Rights Discussed Data Portability"
  label(gdpr_data$q56_rights_discussed_OBJECTION) <- "Q56 Rights Discussed Objection"
  label(gdpr_data$q56_rights_discussed_AUTOMATED_DECISION_MAKING) <- "Q56 Rights Discussed Automated Decision Making"
  label(gdpr_data$q56_rights_discussed_INFORMATION_OBLIGATIONS) <- "Q56 Rights Discussed Information Obligations"
  label(gdpr_data$q56_rights_discussed_NONE_DISCUSSED) <- "Q56 Rights Discussed None Discussed"
  label(gdpr_data$q57_rights_violated_coverage_status) <- "Status of q57_rights_violated_coverage information"
  label(gdpr_data$q57_rights_violated_known) <- "Q57 Rights Violated Known"
  label(gdpr_data$q57_rights_violated_unknown) <- "Q57 Rights Violated Unknown"
  label(gdpr_data$q57_rights_violated_status) <- "Status of q57_rights_violated information"
  label(gdpr_data$q57_rights_violated_exclusivity_conflict) <- "Q57 Rights Violated Exclusivity Conflict"
  label(gdpr_data$q57_rights_violated_ACCESS) <- "Q57 Rights Violated Access"
  label(gdpr_data$q57_rights_violated_RECTIFICATION) <- "Q57 Rights Violated Rectification"
  label(gdpr_data$q57_rights_violated_ERASURE) <- "Q57 Rights Violated Erasure"
  label(gdpr_data$q57_rights_violated_RESTRICTION_OF_PROCESSING) <- "Q57 Rights Violated Restriction Of Processing"
  label(gdpr_data$q57_rights_violated_DATA_PORTABILITY) <- "Q57 Rights Violated Data Portability"
  label(gdpr_data$q57_rights_violated_OBJECTION) <- "Q57 Rights Violated Objection"
  label(gdpr_data$q57_rights_violated_AUTOMATED_DECISION_MAKING) <- "Q57 Rights Violated Automated Decision Making"
  label(gdpr_data$q57_rights_violated_INFORMATION_OBLIGATIONS) <- "Q57 Rights Violated Information Obligations"
  label(gdpr_data$q57_rights_violated_NONE_VIOLATED) <- "Q57 Rights Violated None Violated"
  label(gdpr_data$q57_rights_violated_NOT_DETERMINED) <- "Q57 Rights Violated Not Determined"
  label(gdpr_data$q58_access_issues_coverage_status) <- "Status of q58_access_issues_coverage information"
  label(gdpr_data$q58_access_issues_known) <- "Q58 Access Issues Known"
  label(gdpr_data$q58_access_issues_unknown) <- "Q58 Access Issues Unknown"
  label(gdpr_data$q58_access_issues_status) <- "Status of q58_access_issues information"
  label(gdpr_data$q58_access_issues_exclusivity_conflict) <- "Q58 Access Issues Exclusivity Conflict"
  label(gdpr_data$q58_access_issues_EXCESSIVE_DELAY) <- "Q58 Access Issues Excessive Delay"
  label(gdpr_data$q58_access_issues_EXCESSIVE_FEES) <- "Q58 Access Issues Excessive Fees"
  label(gdpr_data$q58_access_issues_INADEQUATE_RESPONSE) <- "Q58 Access Issues Inadequate Response"
  label(gdpr_data$q58_access_issues_IDENTITY_VERIFICATION_ISSUES) <- "Q58 Access Issues Identity Verification Issues"
  label(gdpr_data$q58_access_issues_SCOPE_LIMITATIONS) <- "Q58 Access Issues Scope Limitations"
  label(gdpr_data$q58_access_issues_NO_ISSUES_FOUND) <- "Q58 Access Issues No Issues Found"
  label(gdpr_data$q58_access_issues_NOT_APPLICABLE) <- "Q58 Access Issues Not Applicable"
  label(gdpr_data$q59_adm_issues_coverage_status) <- "Status of q59_adm_issues_coverage information"
  label(gdpr_data$q59_adm_issues_known) <- "Q59 Adm Issues Known"
  label(gdpr_data$q59_adm_issues_unknown) <- "Q59 Adm Issues Unknown"
  label(gdpr_data$q59_adm_issues_status) <- "Status of q59_adm_issues information"
  label(gdpr_data$q59_adm_issues_exclusivity_conflict) <- "Q59 Adm Issues Exclusivity Conflict"
  label(gdpr_data$q59_adm_issues_LACK_OF_HUMAN_INTERVENTION) <- "Q59 Adm Issues Lack Of Human Intervention"
  label(gdpr_data$q59_adm_issues_INADEQUATE_SAFEGUARDS) <- "Q59 Adm Issues Inadequate Safeguards"
  label(gdpr_data$q59_adm_issues_PROFILING_WITHOUT_CONSENT) <- "Q59 Adm Issues Profiling Without Consent"
  label(gdpr_data$q59_adm_issues_NO_EXPLANATION_PROVIDED) <- "Q59 Adm Issues No Explanation Provided"
  label(gdpr_data$q59_adm_issues_NO_ISSUES_FOUND) <- "Q59 Adm Issues No Issues Found"
  label(gdpr_data$q59_adm_issues_NOT_APPLICABLE) <- "Q59 Adm Issues Not Applicable"
  label(gdpr_data$q61_dpo_issues_coverage_status) <- "Status of q61_dpo_issues_coverage information"
  label(gdpr_data$q61_dpo_issues_known) <- "Q61 Dpo Issues Known"
  label(gdpr_data$q61_dpo_issues_unknown) <- "Q61 Dpo Issues Unknown"
  label(gdpr_data$q61_dpo_issues_status) <- "Status of q61_dpo_issues information"
  label(gdpr_data$q61_dpo_issues_exclusivity_conflict) <- "Q61 Dpo Issues Exclusivity Conflict"
  label(gdpr_data$q61_dpo_issues_NO_DPO_APPOINTED) <- "Q61 Dpo Issues No Dpo Appointed"
  label(gdpr_data$q61_dpo_issues_INADEQUATE_QUALIFICATIONS) <- "Q61 Dpo Issues Inadequate Qualifications"
  label(gdpr_data$q61_dpo_issues_INSUFFICIENT_INDEPENDENCE) <- "Q61 Dpo Issues Insufficient Independence"
  label(gdpr_data$q61_dpo_issues_LACK_OF_RESOURCES) <- "Q61 Dpo Issues Lack Of Resources"
  label(gdpr_data$q61_dpo_issues_INADEQUATE_INVOLVEMENT) <- "Q61 Dpo Issues Inadequate Involvement"
  label(gdpr_data$q61_dpo_issues_CONFLICT_OF_INTEREST) <- "Q61 Dpo Issues Conflict Of Interest"
  label(gdpr_data$q61_dpo_issues_NO_ISSUES_FOUND) <- "Q61 Dpo Issues No Issues Found"
  label(gdpr_data$q61_dpo_issues_NOT_APPLICABLE) <- "Q61 Dpo Issues Not Applicable"
  label(gdpr_data$q64_transfer_violations_coverage_status) <- "Status of q64_transfer_violations_coverage information"
  label(gdpr_data$q64_transfer_violations_known) <- "Q64 Transfer Violations Known"
  label(gdpr_data$q64_transfer_violations_unknown) <- "Q64 Transfer Violations Unknown"
  label(gdpr_data$q64_transfer_violations_status) <- "Status of q64_transfer_violations information"
  label(gdpr_data$q64_transfer_violations_exclusivity_conflict) <- "Q64 Transfer Violations Exclusivity Conflict"
  label(gdpr_data$q64_transfer_violations_NO_ADEQUATE_SAFEGUARDS) <- "Q64 Transfer Violations No Adequate Safeguards"
  label(gdpr_data$q64_transfer_violations_INVALID_TRANSFER_MECHANISM) <- "Q64 Transfer Violations Invalid Transfer Mechanism"
  label(gdpr_data$q64_transfer_violations_SCHREMS_II_ISSUES) <- "Q64 Transfer Violations Schrems Ii Issues"
  label(gdpr_data$q64_transfer_violations_NO_IMPACT_ASSESSMENT) <- "Q64 Transfer Violations No Impact Assessment"
  label(gdpr_data$q64_transfer_violations_INADEQUATE_CONTRACTUAL_CLAUSES) <- "Q64 Transfer Violations Inadequate Contractual Clauses"
  label(gdpr_data$q64_transfer_violations_NOT_APPLICABLE) <- "Q64 Transfer Violations Not Applicable"
  label(gdpr_data$country_code_numeric) <- "Country Code Numeric"
  label(gdpr_data$dpa_numeric) <- "Dpa Numeric"
  label(gdpr_data$isic_section_numeric) <- "Isic Section Numeric"
  label(gdpr_data$fine_eur_missing) <- "Fine Eur Missing"
  label(gdpr_data$turnover_eur_missing) <- "Turnover Eur Missing"
  label(gdpr_data$decision_date_missing) <- "Decision Date Missing"
  label(gdpr_data$decision_date_parsed) <- "Decision Date Parsed"
  label(gdpr_data$days_since_gdpr) <- "Days Since Gdpr"
  label(gdpr_data$fine_positive_flag) <- "Fine Positive Flag"
  label(gdpr_data$fine_log) <- "Fine Log"
  label(gdpr_data$fine_sqrt) <- "Fine Sqrt"
  label(gdpr_data$fine_category) <- "Fine Category"
  label(gdpr_data$n_principles_discussed_high) <- "N Principles Discussed High"
  label(gdpr_data$n_principles_violated_high) <- "N Principles Violated High"
  label(gdpr_data$n_corrective_measures_high) <- "N Corrective Measures High"
  label(gdpr_data$enforcement_severity_index) <- "Enforcement Severity Index"

}

# Summary statistics
cat("Dataset loaded successfully\n")
cat("Dimensions:", nrow(gdpr_data), "rows,", ncol(gdpr_data), "columns\n")
cat("Decision date range:", min(gdpr_data$decision_date, na.rm=TRUE), "to", max(gdpr_data$decision_date, na.rm=TRUE), "\n")

# Basic descriptive statistics
summary(gdpr_data[c("fine_eur", "decision_year", "country_group", "breach_case")])
