"""Phase 2 – uniformity testing for GDPR enforcement outcomes.

This module builds on the Phase 1 artefacts to assess whether enforcement
outcomes are conditionally independent of jurisdiction once facts are taken
into account.  It provides utilities for:

* cross-fitted nuisance modelling (orthogonalised residuals);
* conditional randomisation tests against country and DPA groupings;
* matched-pair disparity statistics across the twin constructions;
* distributional equality diagnostics (KS/EMD/quantile contrasts);
* hierarchical invariance checks via mixed-effects models; and
* calibration summaries across risk bands.

All heavy lifting happens with pandas/NumPy/Statsmodels/Scikit-learn, keeping
dependencies aligned with the rest of the analysis stack.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
import warnings
from typing import Iterable, Mapping, Sequence

import numpy as np
import pandas as pd
from scipy import stats
from sklearn.linear_model import Ridge, SGDClassifier
from sklearn.model_selection import KFold
import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.stats.contingency_tables import mcnemar
from statsmodels.stats.multitest import multipletests
from statsmodels.stats.weightstats import DescrStatsW
from statsmodels.tools.sm_exceptions import ValueWarning as SMValueWarning

warnings.filterwarnings(
    "once",
    category=RuntimeWarning,
    message=".*ks_2samp: Exact calculation unsuccessful.*",
)

from .config import FACTS_CONFIG, EvennessPaths


RISK_VENTILE_QUANTILES = (0.25, 0.5, 0.75, 0.9)
SUPPORTED_OUTCOMES = tuple(
    col
    for col in (
        "fine_positive",
        "fine_eur",
        "fine_log1p",
        "enforcement_severity_index",
        "q53_powers_WARNING",
        "q53_powers_REPRIMAND",
        "q53_powers_ADMINISTRATIVE_FINE",
        "q53_powers_LIMITATION_PROHIBITION_OF_PROCESSING",
        "q53_powers_RECTIFICATION_ERASURE_RESTRICTION",
        "q53_powers_BRING_PROCESSING_INTO_COMPLIANCE",
        "q53_powers_COMMUNICATE_BREACH_TO_SUBJECTS",
    )
    if col in FACTS_CONFIG.outcome_columns
)


@dataclass
class PhaseTwoOutputs:
    """Bundle of artefacts generated by :func:`run_phase_two`."""

    residuals: pd.DataFrame
    jurisdiction_effects: pd.DataFrame
    joint_tests: pd.DataFrame
    paired_tests: pd.DataFrame
    distribution_tests: pd.DataFrame
    quantile_contrasts: pd.DataFrame
    calibration: pd.DataFrame
    variance_components: pd.DataFrame


def _feature_columns(df: pd.DataFrame, outcomes: Sequence[str]) -> list[str]:
    exclude = {
        "decision_id",
        "country_code",
        "dpa_name_canonical",
        "country_year",
        "country_year_weight",
        "time_observed",
        "ipw_time_observed",
    }
    exclude.update(outcomes)
    exclude.update(col for col in df.columns if col.endswith("_status"))
    exclude.update(col for col in df.columns if col.endswith("_coverage"))
    exclude.update(col for col in df.columns if col.endswith("_coverage_status"))
    features: list[str] = []
    for col in df.columns:
        if col in exclude:
            continue
        if df[col].dtype == "O":
            continue
        features.append(col)
    return features


def _base_model(kind: str):
    if kind == "binary":
        return SGDClassifier(loss="log_loss", penalty="l2", max_iter=2000, tol=1e-4, random_state=0)
    return Ridge(alpha=1.0)


def _cross_fitted_predictions(
    X: pd.DataFrame,
    y: pd.Series,
    kind: str,
    sample_weight: pd.Series | None = None,
    n_splits: int = 5,
    random_state: int = 42,
) -> pd.Series:
    """Return cross-fitted predictions for ``y`` using histogram GBDT models."""

    mask = y.notna()
    if mask.sum() < 2:
        return pd.Series(np.nan, index=y.index)

    X_valid = X.loc[mask].fillna(0.0)
    y_valid = y.loc[mask]
    weights = sample_weight.loc[mask] if sample_weight is not None else None

    n_splits = min(n_splits, max(2, len(X_valid) // 5 or 2))
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    preds = pd.Series(index=y.index, dtype=float)

    for train_idx, test_idx in kf.split(X_valid):
        X_train, X_test = X_valid.iloc[train_idx], X_valid.iloc[test_idx]
        y_train = y_valid.iloc[train_idx]
        model = _base_model(kind)
        if weights is not None:
            w_train = weights.iloc[train_idx]
            model.fit(X_train, y_train, sample_weight=w_train)
        else:
            model.fit(X_train, y_train)
        if kind == "binary":
            pred = model.predict_proba(X_test)[:, 1]
        else:
            pred = model.predict(X_test)
        preds.loc[X_valid.index[test_idx]] = pred

    return preds


def _weighted_quantile(values: np.ndarray, weights: np.ndarray, quantile: float) -> float:
    if len(values) == 0:
        return float("nan")
    order = np.argsort(values)
    values = values[order]
    weights = weights[order]
    cum_weights = np.cumsum(weights)
    threshold = quantile * cum_weights[-1]
    idx = np.searchsorted(cum_weights, threshold, side="right")
    idx = min(idx, len(values) - 1)
    return float(values[idx])


def _prepare_residuals(
    df: pd.DataFrame,
    outcomes: Sequence[str],
    dataset_label: str,
    features: Sequence[str],
    sample_weight: pd.Series,
    nuisance_weight: pd.Series,
) -> tuple[pd.DataFrame, list[pd.DataFrame]]:
    records: list[pd.Series] = []
    predictions: list[pd.DataFrame] = []
    feature_frame = df[features]

    for outcome in outcomes:
        if outcome not in df.columns:
            continue
        kind = "binary" if outcome == "fine_positive" or outcome.startswith("q53_powers_") else "continuous"
        y = df[outcome]
        preds = _cross_fitted_predictions(feature_frame, y, kind, nuisance_weight)
        residual = y - preds
        payload = pd.DataFrame(
            {
                "decision_id": df["decision_id"],
                "dataset": dataset_label,
                "outcome": outcome,
                "prediction": preds,
                "residual": residual,
                "analysis_weight": sample_weight,
                "nuisance_weight": nuisance_weight,
                "country_code": df["country_code"],
                "dpa_name_canonical": df["dpa_name_canonical"],
            }
        )
        predictions.append(payload)

    residuals = pd.concat(predictions, axis=0, ignore_index=True)
    return residuals, predictions


def _jurisdiction_models(
    residuals: pd.DataFrame,
    group_col: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    if residuals[group_col].nunique() < 2:
        return pd.DataFrame(), pd.DataFrame()

    residuals = residuals.dropna(subset=["residual", group_col])
    if residuals.empty:
        return pd.DataFrame(), pd.DataFrame()

    residuals = residuals.copy()
    counts = residuals[group_col].value_counts()
    valid_levels = counts[counts >= 2].index
    residuals = residuals[residuals[group_col].isin(valid_levels)]
    if residuals[group_col].nunique() < 2:
        return pd.DataFrame(), pd.DataFrame()

    categories = residuals[group_col].astype(str)
    levels = sorted(pd.unique(categories))
    if len(levels) < 2:
        return pd.DataFrame(), pd.DataFrame()

    design = pd.get_dummies(categories, drop_first=True).astype(float)
    design = sm.add_constant(design, has_constant="add")
    weights = residuals["analysis_weight"].fillna(1.0)
    model = sm.WLS(residuals["residual"], design, weights=weights)
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            category=SMValueWarning,
            message="covariance of constraints does not have full rank",
        )
        result = model.fit(cov_type="cluster", cov_kwds={"groups": residuals["dpa_name_canonical"]})

    cov = result.cov_params()
    effects_records: list[dict[str, object]] = []
    baseline = levels[0]
    for level in levels:
        if level == baseline:
            effect = result.params["const"]
            var = cov.loc["const", "const"]
        else:
            coef_name = level
            if coef_name not in result.params:
                continue
            effect = result.params["const"] + result.params[coef_name]
            var = (
                cov.loc["const", "const"]
                + cov.loc[coef_name, coef_name]
                + 2 * cov.loc["const", coef_name]
            )
        std_err = float(np.sqrt(max(var, 0))) if np.isfinite(var) else np.nan
        tvalue = effect / std_err if std_err and np.isfinite(std_err) else np.nan
        pvalue = 2 * stats.norm.sf(abs(tvalue)) if np.isfinite(tvalue) else np.nan
        effects_records.append(
            {
                "jurisdiction": level,
                "effect": float(effect),
                "std_err": std_err,
                "tvalue": float(tvalue) if np.isfinite(tvalue) else np.nan,
                "pvalue": float(pvalue) if np.isfinite(pvalue) else np.nan,
                "n_obs": int(result.nobs),
            }
        )

    if len(result.params) <= 1:
        joint = None
    else:
        dmatrix = np.eye(len(result.params))
        if "const" in result.params.index:
            mask = result.params.index != "const"
            dmatrix = dmatrix[mask]
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore",
                category=SMValueWarning,
                message="covariance of constraints does not have full rank",
            )
            joint = result.f_test(dmatrix) if dmatrix.size else None
    joint_df = pd.DataFrame(
        {
            "statistic": float(joint.statistic) if joint is not None else np.nan,
            "pvalue": float(joint.pvalue) if joint is not None else np.nan,
            "df_denom": float(getattr(joint, "df_denom", result.df_resid)) if joint is not None else np.nan,
        },
        index=[0],
    )

    return pd.DataFrame(effects_records), joint_df


def _apply_fdr(frame: pd.DataFrame, column: str = "pvalue", adj_column: str = "pvalue_fdr") -> pd.DataFrame:
    if frame.empty or column not in frame:
        frame[adj_column] = []
        return frame
    mask = frame[column].notna()
    if mask.sum() == 0:
        frame[adj_column] = np.nan
        return frame
    _, qvals, _, _ = multipletests(frame.loc[mask, column], method="fdr_bh")
    frame.loc[mask, adj_column] = qvals
    frame.loc[~mask, adj_column] = np.nan
    return frame


def _pair_label(a: str, b: str) -> str:
    if pd.isna(a) or pd.isna(b):
        return "MISSING"
    ordered = sorted([str(a), str(b)])
    return f"{ordered[0]} vs {ordered[1]}"


def _prepare_pairs_from_edges(
    edges: pd.DataFrame,
    index_df: pd.DataFrame,
    outcomes: Sequence[str],
    dataset_label: str,
    source_suffix: str = "_source",
    target_suffix: str = "_target",
) -> pd.DataFrame:
    if edges.empty:
        return pd.DataFrame()

    lookup = index_df.set_index("decision_id")
    merged = edges.merge(
        lookup[["country_code", "dpa_name_canonical"] + list(outcomes)],
        left_on="source_id",
        right_index=True,
        how="left",
    )
    merged = merged.merge(
        lookup[["country_code", "dpa_name_canonical"] + list(outcomes)],
        left_on="target_id",
        right_index=True,
        how="left",
        suffixes=(source_suffix, target_suffix),
    )
    merged["dataset"] = dataset_label
    merged["country_pair"] = merged.apply(
        lambda row: _pair_label(row["country_code" + source_suffix], row["country_code" + target_suffix]),
        axis=1,
    )
    merged["dpa_pair"] = merged.apply(
        lambda row: _pair_label(row["dpa_name_canonical" + source_suffix], row["dpa_name_canonical" + target_suffix]),
        axis=1,
    )
    return merged


def _prepare_pairs_from_cem(
    cem: pd.DataFrame,
    index_df: pd.DataFrame,
    outcomes: Sequence[str],
    dataset_label: str,
) -> pd.DataFrame:
    if cem.empty:
        return pd.DataFrame()

    merged = cem.merge(cem, on="stratum_id", suffixes=("_source", "_target"))
    merged = merged.loc[merged["decision_id_source"] < merged["decision_id_target"]]
    merged = merged.loc[merged["country_code_source"] != merged["country_code_target"]]
    if merged.empty:
        return pd.DataFrame()

    lookup = index_df.set_index("decision_id")
    payload = merged.merge(
        lookup[["dpa_name_canonical"] + list(outcomes)],
        left_on="decision_id_source",
        right_index=True,
        how="left",
    )
    payload = payload.merge(
        lookup[["dpa_name_canonical"] + list(outcomes)],
        left_on="decision_id_target",
        right_index=True,
        how="left",
        suffixes=("_source", "_target"),
    )
    payload["weight"] = np.sqrt(payload["weight_source"] * payload["weight_target"])
    payload["dataset"] = dataset_label
    payload["source_id"] = payload["decision_id_source"]
    payload["target_id"] = payload["decision_id_target"]
    payload["source_country"] = payload["country_code_source"]
    payload["target_country"] = payload["country_code_target"]
    payload["country_pair"] = payload.apply(
        lambda row: _pair_label(row["source_country"], row["target_country"]),
        axis=1,
    )
    payload["dpa_pair"] = payload.apply(
        lambda row: _pair_label(row["dpa_name_canonical_source"], row["dpa_name_canonical_target"]),
        axis=1,
    )
    return payload


def _paired_statistics(
    pairs: pd.DataFrame,
    outcome: str,
    group_col: str,
) -> pd.DataFrame:
    source_col = f"{outcome}_source"
    target_col = f"{outcome}_target"
    if source_col not in pairs or target_col not in pairs:
        return pd.DataFrame()

    records: list[dict[str, object]] = []
    for name, group in pairs.groupby(group_col):
        values = group[[source_col, target_col, "weight"]].dropna()
        if values.empty:
            continue

        weights = values["weight"].fillna(1.0)
        diff = values[source_col] - values[target_col]
        weight_sum = float(weights.sum())
        n_pairs = int(len(diff))

        mean_diff = float(np.average(diff, weights=weights)) if weight_sum > 0 else float("nan")
        entry: dict[str, object] = {
            group_col: name,
            "outcome": outcome,
            "n_pairs": n_pairs,
            "weight_sum": weight_sum,
            "mean_diff": mean_diff,
            "ci_lower": np.nan,
            "ci_upper": np.nan,
            "t_stat": np.nan,
            "pvalue_t": np.nan,
        }

        if n_pairs >= 2 and weight_sum > 0:
            weights_array = weights.to_numpy()
            diff_array = diff.to_numpy()
            sum_w2 = float(np.sum(weights_array ** 2))
            effective_n = (weight_sum ** 2) / sum_w2 if sum_w2 > 0 else 0.0
            if effective_n > 1.0:
                ddof = 1 if effective_n > 1 else 0
                with np.errstate(all="ignore"):
                    stats_w = DescrStatsW(diff_array, weights=weights_array, ddof=ddof)
                    try:
                        lower, upper = stats_w.tconfint_mean()
                    except Exception:
                        lower, upper = (np.nan, np.nan)
                    try:
                        t_stat, pvalue, _ = stats_w.ttest_mean(0)
                    except Exception:
                        t_stat, pvalue = (np.nan, np.nan)
                entry.update(
                    {
                        "ci_lower": float(lower) if np.isfinite(lower) else np.nan,
                        "ci_upper": float(upper) if np.isfinite(upper) else np.nan,
                        "t_stat": float(t_stat) if np.isfinite(t_stat) else np.nan,
                        "pvalue_t": float(pvalue) if np.isfinite(pvalue) else np.nan,
                    }
                )

        if outcome == "fine_positive" or outcome.startswith("q53_powers_"):
            mask_01 = (values[source_col] == 0) & (values[target_col] == 1)
            mask_10 = (values[source_col] == 1) & (values[target_col] == 0)
            n01 = float(weights.loc[mask_01].sum())
            n10 = float(weights.loc[mask_10].sum())
            if (n01 + n10) > 0:
                table = np.array([[0.0, n01], [n10, 0.0]], dtype=float)
                with np.errstate(all="ignore"):
                    mcnemar_result = mcnemar(table, exact=False)
                entry["pvalue_mcnemar"] = float(mcnemar_result.pvalue)
                entry["mcnemar_stat"] = float(mcnemar_result.statistic)
                entry["net_up_minus_down"] = float(n10 - n01)
            else:
                entry["pvalue_mcnemar"] = np.nan
                entry["mcnemar_stat"] = np.nan
                entry["net_up_minus_down"] = 0.0
        records.append(entry)
    return pd.DataFrame(records)


def _distribution_tests(
    base: pd.DataFrame,
    strata: pd.DataFrame,
    strata_key: str,
    outcomes: Sequence[str],
    weight_col: str,
    dataset_label: str,
    level_label: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    if strata.empty:
        return pd.DataFrame(), pd.DataFrame()

    records: list[dict[str, object]] = []
    quantiles: list[dict[str, object]] = []
    join_cols = ["decision_id", weight_col] + list(outcomes)
    if "country_code" in base.columns:
        join_cols.append("country_code")
    join = base[join_cols].copy()
    if "country_code" in join.columns:
        join = join.rename(columns={"country_code": "analysis_country"})
    working = strata.merge(join, on="decision_id", how="inner")
    if working.empty:
        return pd.DataFrame(), pd.DataFrame()

    for stratum_id, group in working.groupby(strata_key):
        country_col = "analysis_country" if "analysis_country" in group.columns else "country_code"
        if country_col not in group:
            continue
        countries = group[country_col].dropna().unique()
        if len(countries) < 2:
            continue
        for outcome in outcomes:
            if outcome not in group:
                continue
            for country_a, country_b in combinations(sorted(countries), 2):
                sample_a = group.loc[group[country_col] == country_a, outcome].dropna()
                sample_b = group.loc[group[country_col] == country_b, outcome].dropna()
                if sample_a.empty or sample_b.empty:
                    continue
                weights_a = group.loc[sample_a.index, weight_col].fillna(1.0)
                weights_b = group.loc[sample_b.index, weight_col].fillna(1.0)
                with warnings.catch_warnings():
                    warnings.filterwarnings(
                        "ignore",
                        category=RuntimeWarning,
                        message="divide by zero encountered in divide",
                    )
                    ks_stat, ks_p = stats.ks_2samp(sample_a, sample_b, method="asymp")
                emd = stats.wasserstein_distance(sample_a, sample_b, weights_a, weights_b)
                record = {
                    "dataset": dataset_label,
                    "level": level_label,
                    "stratum": stratum_id,
                    "outcome": outcome,
                    "pair": _pair_label(country_a, country_b),
                    "ks_stat": float(ks_stat),
                    "ks_pvalue": float(ks_p),
                    "emd": float(emd),
                    "n_a": int(len(sample_a)),
                    "n_b": int(len(sample_b)),
                }
                records.append(record)
                for tau in RISK_VENTILE_QUANTILES:
                    qa = _weighted_quantile(sample_a.to_numpy(), weights_a.to_numpy(), tau)
                    qb = _weighted_quantile(sample_b.to_numpy(), weights_b.to_numpy(), tau)
                    quantiles.append(
                        {
                            "dataset": dataset_label,
                            "level": level_label,
                            "stratum": stratum_id,
                            "outcome": outcome,
                            "pair": _pair_label(country_a, country_b),
                            "quantile": tau,
                            "qa": qa,
                            "qb": qb,
                            "diff": qa - qb,
                        }
                    )

    dist_frame = pd.DataFrame(records)
    quant_frame = pd.DataFrame(quantiles)
    return dist_frame, quant_frame


def _calibration_by_band(
    base: pd.DataFrame,
    risk: pd.DataFrame,
    dataset_label: str,
    weight_col: str,
) -> pd.DataFrame:
    if risk.empty:
        return pd.DataFrame()
    joined = risk.merge(base[["decision_id", "fine_positive", "fine_log1p", weight_col]], on="decision_id", how="inner")
    if joined.empty:
        return pd.DataFrame()
    records: list[dict[str, object]] = []
    for ventile, group in joined.groupby("risk_ventile"):
        weights = group[weight_col].fillna(1.0)
        w = weights.to_numpy()
        obs = group["fine_positive"].to_numpy()
        pred = group["pred_fine_positive"].to_numpy()
        if len(pred) == 0:
            continue
        mean_pred = float(np.average(pred, weights=w))
        mean_obs = float(np.average(obs, weights=w))
        brier = float(np.average((pred - obs) ** 2, weights=w))
        log_pred = group.get("pred_log_fine", pd.Series(np.nan, index=group.index)).to_numpy()
        log_obs = group.get("fine_log1p", pd.Series(np.nan, index=group.index)).to_numpy()
        log_bias = float(np.average(log_obs - log_pred, weights=w)) if np.isfinite(log_pred).any() else np.nan
        records.append(
            {
                "dataset": dataset_label,
                "risk_ventile": int(ventile),
                "mean_pred": mean_pred,
                "mean_obs": mean_obs,
                "brier": brier,
                "log_bias": log_bias,
                "n_cases": int(len(group)),
                "weight_sum": float(weights.sum()),
            }
        )
    return pd.DataFrame(records)


def _variance_components(
    df: pd.DataFrame,
    outcome: str,
    features: Sequence[str],
    weight_col: str,
    random_slopes: Sequence[str],
) -> pd.DataFrame:
    if outcome not in df.columns:
        return pd.DataFrame()
    data = df.dropna(subset=[outcome])
    if data.empty:
        return pd.DataFrame()

    rhs_terms: list[str] = []
    for feature in features:
        if feature in data.columns:
            if data[feature].dtype == "O":
                rhs_terms.append(f"C({feature})")
            else:
                rhs_terms.append(feature)
    formula = outcome + " ~ " + " + ".join(rhs_terms) if rhs_terms else outcome + " ~ 1"

    weights = data[weight_col].fillna(1.0)

    random = [term for term in random_slopes if term in data.columns]
    re_formula = "1"
    if random:
        re_formula = "1 + " + " + ".join(random)

    try:
        model = smf.mixedlm(
            formula,
            data,
            groups=data["dpa_name_canonical"],
            re_formula=re_formula,
            vc_formula={"country": "0 + C(country_code)"},
            weights=weights,
        )
        result = model.fit(method="lbfgs", reml=True, maxiter=200)
    except Exception:
        return pd.DataFrame()

    vc = result.cov_re
    if vc is None or vc.empty:
        return pd.DataFrame()

    components: list[dict[str, object]] = []
    dpa_var = float(vc.iloc[0, 0]) if vc.size else float("nan")
    if np.isfinite(dpa_var):
        components.append({"component": "DPA", "variance": dpa_var})
    country_var = float(result.vcomp["country"]) if "country" in result.vcomp else float("nan")
    if np.isfinite(country_var):
        components.append({"component": "Country", "variance": country_var})
    resid_var = float(result.scale)
    if np.isfinite(resid_var):
        components.append({"component": "Residual", "variance": resid_var})
    total = sum(entry["variance"] for entry in components if np.isfinite(entry["variance"]))
    for entry in components:
        entry["outcome"] = outcome
        entry["icc"] = entry["variance"] / total if total else np.nan
    return pd.DataFrame(components)


def run_phase_two(
    paths: EvennessPaths | None = None,
    outcomes: Sequence[str] | None = None,
    n_splits: int = 5,
    random_state: int = 42,
) -> PhaseTwoOutputs:
    """Execute the Phase 2 uniformity workflow."""

    paths = paths or EvennessPaths()
    paths.ensure()

    X_full = pd.read_parquet(paths.x_full)
    X_timeobs = pd.read_parquet(paths.x_timeobs)
    outcomes = [col for col in (outcomes or SUPPORTED_OUTCOMES) if col in X_full.columns]

    features = _feature_columns(X_full, outcomes)

    residual_frames: list[pd.DataFrame] = []

    full_weights = X_full.get("country_year_weight", pd.Series(1.0, index=X_full.index)).fillna(1.0)
    nuisance_full = full_weights
    residual_full, _ = _prepare_residuals(
        X_full,
        outcomes,
        dataset_label="full",
        features=features,
        sample_weight=full_weights,
        nuisance_weight=nuisance_full,
    )
    residual_frames.append(residual_full)

    if "ipw_time_observed" in X_timeobs.columns:
        time_weights = (
            X_timeobs["country_year_weight"].fillna(1.0)
            * X_timeobs["ipw_time_observed"].fillna(1.0)
        )
        nuisance_time = X_timeobs["ipw_time_observed"].fillna(1.0)
    else:
        time_weights = X_timeobs.get("country_year_weight", pd.Series(1.0, index=X_timeobs.index)).fillna(1.0)
        nuisance_time = time_weights

    residual_time, _ = _prepare_residuals(
        X_timeobs,
        outcomes,
        dataset_label="time_observed",
        features=features,
        sample_weight=time_weights,
        nuisance_weight=nuisance_time,
    )
    residual_frames.append(residual_time)

    residuals = pd.concat(residual_frames, ignore_index=True)

    jurisdiction_records: list[pd.DataFrame] = []
    joint_records: list[pd.DataFrame] = []

    for (dataset, outcome), subset in residuals.groupby(["dataset", "outcome"]):
        for level, label in (("country_code", "Country"), ("dpa_name_canonical", "DPA")):
            effects, joint = _jurisdiction_models(subset, level)
            if not effects.empty:
                effects["dataset"] = dataset
                effects["outcome"] = outcome
                effects["level"] = label
                effects["ci_lower"] = effects["effect"] - 1.96 * effects["std_err"]
                effects["ci_upper"] = effects["effect"] + 1.96 * effects["std_err"]
                jurisdiction_records.append(effects)
            if not joint.empty:
                joint["dataset"] = dataset
                joint["outcome"] = outcome
                joint["level"] = label
                joint_records.append(joint)

    jurisdiction_effects = pd.concat(jurisdiction_records, ignore_index=True) if jurisdiction_records else pd.DataFrame()
    joint_tests = pd.concat(joint_records, ignore_index=True) if joint_records else pd.DataFrame()

    jurisdiction_effects = _apply_fdr(jurisdiction_effects)
    joint_tests = _apply_fdr(joint_tests)

    # Paired disparities across twin constructions
    index_df = X_full[["decision_id", "country_code", "dpa_name_canonical"] + list(outcomes)].copy()
    gower_within = pd.read_parquet(paths.twins_gower_within)
    gower_cross = pd.read_parquet(paths.twins_gower_cross)
    cem = pd.read_parquet(paths.twins_cem)

    pair_frames: list[pd.DataFrame] = []
    for dataset_label, frame in (
        ("gower_within", gower_within),
        ("gower_cross", gower_cross),
    ):
        prepared = _prepare_pairs_from_edges(frame, index_df, outcomes, dataset_label)
        if prepared.empty:
            continue
        for group_col in ("country_pair", "dpa_pair"):
            stats_frame = _paired_statistics(prepared, "fine_positive", group_col)
            if not stats_frame.empty:
                stats_frame["dataset"] = dataset_label
                stats_frame["group_level"] = group_col
                pair_frames.append(stats_frame)
            for outcome in outcomes:
                if outcome == "fine_positive":
                    continue
                stats_frame = _paired_statistics(prepared, outcome, group_col)
                if stats_frame.empty:
                    continue
                stats_frame["dataset"] = dataset_label
                stats_frame["group_level"] = group_col
                pair_frames.append(stats_frame)

    cem_pairs = _prepare_pairs_from_cem(cem, index_df, outcomes, "cem")
    if not cem_pairs.empty:
        for group_col in ("country_pair", "dpa_pair"):
            for outcome in outcomes:
                stats_frame = _paired_statistics(cem_pairs, outcome, group_col)
                if stats_frame.empty:
                    continue
                stats_frame["dataset"] = "cem"
                stats_frame["group_level"] = group_col
                pair_frames.append(stats_frame)

    paired_tests = pd.concat(pair_frames, ignore_index=True) if pair_frames else pd.DataFrame()
    paired_tests = _apply_fdr(paired_tests, column="pvalue_t", adj_column="pvalue_t_fdr")
    if "pvalue_mcnemar" in paired_tests.columns:
        paired_tests = _apply_fdr(paired_tests, column="pvalue_mcnemar", adj_column="pvalue_mcnemar_fdr")

    # Distributional equality diagnostics
    distribution_frames: list[pd.DataFrame] = []
    quantile_frames: list[pd.DataFrame] = []

    for dataset_label, base_df, weight_col in (
        ("full", X_full.assign(analysis_weight=full_weights), "analysis_weight"),
        ("time_observed", X_timeobs.assign(analysis_weight=time_weights.reindex(X_timeobs.index, fill_value=1.0)), "analysis_weight"),
    ):
        cem_dist, cem_quant = _distribution_tests(
            base_df,
            pd.read_parquet(paths.twins_cem),
            "stratum_id",
            [out for out in outcomes if out != "fine_positive" or out in base_df],
            weight_col,
            dataset_label,
            "CEM",
        )
        if not cem_dist.empty:
            distribution_frames.append(cem_dist)
            quantile_frames.append(cem_quant)
        risk = pd.read_parquet(paths.twins_riskbands)
        risk_dist, risk_quant = _distribution_tests(
            base_df,
            risk,
            "risk_ventile",
            [out for out in outcomes if out != "fine_positive" or out in base_df],
            weight_col,
            dataset_label,
            "RiskBand",
        )
        if not risk_dist.empty:
            distribution_frames.append(risk_dist)
            quantile_frames.append(risk_quant)

    distribution_tests = pd.concat(distribution_frames, ignore_index=True) if distribution_frames else pd.DataFrame()
    quantile_contrasts = pd.concat(quantile_frames, ignore_index=True) if quantile_frames else pd.DataFrame()
    distribution_tests = _apply_fdr(distribution_tests, column="ks_pvalue", adj_column="ks_pvalue_fdr")

    # Calibration summaries
    calibration_frames: list[pd.DataFrame] = []
    risk = pd.read_parquet(paths.twins_riskbands)
    calibration_frames.append(
        _calibration_by_band(X_full.assign(weight=full_weights), risk, "full", "weight")
    )
    calibration_frames.append(
        _calibration_by_band(X_timeobs.assign(weight=time_weights), risk, "time_observed", "weight")
    )
    calibration = pd.concat([frame for frame in calibration_frames if frame is not None], ignore_index=True)

    # Mixed-effects variance components (hierarchical invariance)
    fixed_features = [
        "days_since_gdpr",
        "n_principles_violated",
        "n_corrective_measures",
        "country_year_weight",
        "case_origin",
        "organization_size_tier",
        "organization_type",
    ]
    random_terms = [
        "q25_sensitive_data_ARTICLE_9_SPECIAL_CATEGORY",
        "q25_sensitive_data_ARTICLE_10_CRIMINAL",
        "q46_vuln_CHILDREN",
        "q47_remedial_RECTIFICATION_ERASURE_RESTRICTION",
    ]
    variance_frames: list[pd.DataFrame] = []
    for outcome in outcomes:
        if outcome in ("fine_positive",) or outcome.startswith("q53_powers_"):
            continue
        frame = _variance_components(X_full, outcome, fixed_features, "country_year_weight", random_terms)
        if not frame.empty:
            variance_frames.append(frame)
    variance_components = pd.concat(variance_frames, ignore_index=True) if variance_frames else pd.DataFrame()

    # Persist artefacts
    residuals.to_parquet(paths.uniformity_residuals, index=False)
    jurisdiction_effects.to_csv(paths.uniformity_effects_csv, index=False)
    joint_tests.to_csv(paths.uniformity_joint_csv, index=False)
    paired_tests.to_csv(paths.uniformity_pairs_csv, index=False)
    distribution_tests.to_csv(paths.uniformity_distribution_csv, index=False)
    quantile_contrasts.to_csv(paths.uniformity_quantiles_csv, index=False)
    calibration.to_csv(paths.uniformity_calibration_csv, index=False)
    variance_components.to_csv(paths.uniformity_variance_csv, index=False)

    return PhaseTwoOutputs(
        residuals=residuals,
        jurisdiction_effects=jurisdiction_effects,
        joint_tests=joint_tests,
        paired_tests=paired_tests,
        distribution_tests=distribution_tests,
        quantile_contrasts=quantile_contrasts,
        calibration=calibration,
        variance_components=variance_components,
    )


__all__ = ["run_phase_two", "PhaseTwoOutputs"]

